### ISSUE TITLE
dont add path separators automatically

### ISSUE THREAD

**Issue by marcelloceschia** [scope01-GmbH/ScopRedirecter#1]
Thank you for this nice plugin, I tried this for an customer - but we found one issue within the redirection function.

E.g. if we try to redirect to a product with an specific article number, this is only working if we set the full redirection URI, not only the path part. The reason is, if we set target as `/product?number=321319.4` the code at https://github.com/scope01-GmbH/ScopRedirecter/blob/master/Subscriber/RequestSubscriber.php#L123 will add a / at the end, so the result is `/product?number=321319.4/` - but thats not the valid product uri.
I think the code should not change the value choosen in the target field

**Comment by enesaktay** [comment]
@KHomburg @ascheider 
Agree with this issue. Would really be awesome if you did fix it. 
Basically what would fix this issue is if the plugin took the "Target url" exactly as it is and redirect to that and don't add a "/" randomly at the end sometimes and sometimes not.

Thanks in advance!

**Comment by timotrautmann** [comment]
@marcelloceschia @enesaktay have a look at the new release version 1.0.6. There are a lot of improvements and you can configure your requests behaviour in plugin settings. 👍
